name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install --project-directory=./

    - name: Archive
      run: |
        xcodebuild archive -workspace AltStore.xcworkspace -scheme AltStore \
        -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' \
        -archivePath $GITHUB_WORKSPACE/build/AltStore.xcarchive \
        EXCLUDED_SOURCE_FILE_NAMES="AltStoreCore/Localizable.strings" \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGNING_REQUIRED=NO

    - name: Export .ipa file
      run: |
        xcodebuild -exportArchive \
        -archivePath $GITHUB_WORKSPACE/build/AltStore.xcarchive \
        -exportPath $GITHUB_WORKSPACE/build/AltStore.ipa \
        -exportOptionsPlist $GITHUB_WORKSPACE/exportOptions.plist \
        CODE_SIGNING_ALLOWED=NO